name: Build_Bootstrap

on:
  push:
    tags:
      - "*.*"

jobs:
  build:
    name: Build Bootstrap
    runs-on: macos-13

    steps:
#      - name: Setup Xcode version
#        uses: maxim-lobanov/setup-xcode@v1
#        with:
#          xcode-version: 15.1
    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Theos
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"

      - name: Setup Environment
        run: echo "THEOS=~/theos" >> $GITHUB_ENV

#      - name: Checkout ColorfulX/main
#        uses: actions/checkout@main
#        with:
#          repository: Lakr233/ColorfulX
#          path: ColorfulX

      - name: Build Bootstrap
        run: |
          make package
          mv ./packages/Bootstrap.tipa ./packages/Bootstrap_CCUI_1.x.tipa
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Bootstrap
          path: ./packages/*.tipa

      - name: Setup build environment
        run: |
          echo "Available SDKs: $(find $THEOS/sdks -name "*.sdk" -maxdepth 1 -print)"
          echo "FINALPACKAGE=1" >> $GITHUB_ENV
          cd $GITHUB_WORKSPACE/Bootstrap
          git fetch --tags
      
          # Extract the tag from GITHUB_REF
          TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          echo "GIT_TAG=$TAG" >> $GITHUB_ENV


      - name: Generate Tag & Release Name
        id: generate_name
        run: |
          # Using the previously obtained GIT_TAG as the release tag and name
          release_tag="${{ env.GIT_TAG }}"
          release_name="${{ env.GIT_TAG }}"
          echo "release_name=$release_name" >> $GITHUB_OUTPUT
          echo "release_tag=$release_tag" >> $GITHUB_OUTPUT

   
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./packages/*.tipa
          name: ${{ steps.generate_name.outputs.release_name }}
          tag: ${{ steps.generate_name.outputs.release_tag }}
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
